apiVersion: v1
kind: Service
metadata:
  name: qemu-exporter
  namespace: openstack
  labels: {app: qemu-exporter}
spec:
  selector: {app: qemu-exporter}
  ports:
    - {name: metrics, port: 9179, targetPort: 9179}
